language: rust
cache: cargo
matrix:
  include:
    - name: "Linux (no features)"
      os: linux
      dist: xenial
      env: DEPLOYABLE=true DEPLOY_NAME=linux.no-features
    - name: "Linux (all features)"
      os: linux
      dist: xenial
      services: xvfb
      addons:
        apt:
          packages:
            - libdbus-1-dev
            - libxcb-shape0
            - libxcb-shape0-dev
            - libxcb-xfixes0-dev
            - libxcb-xfixes0
      env: OTPCLI_ALL_FEATURES=true DEPLOY_NAME=linux.all-features
    - name: "mac os"
      os: osx
      env: DEPLOY_NAME=osx
before_script:
- rustup component add rustfmt
- rustup component add clippy
script:
- .ci/build.sh
before_deploy:
  - .ci/setup_deploy.sh
deploy:
  - provider: releases
    api_key:
      secure: i/jxVhjIryCp2FZhoHvL/YaMtTzsR8AdmhmfBiFEhCbhwY9Qa8cbxdmwMyguZ+zdSQYyYuoOT9SVcOqF0RmeqR0ubeQEkUx8aRKzX+4G1a16Tt4lMHp5IXHgBfDVrwg1iK+ZquYVmOQfoAuMMpglimP48nZRo3xhfnlhlkTTY1NYsLP2xlz9AjicYrTV/Yfx28rAVnr27lV6PCygo3w9w8vRNLIabJPtuTgCqr+89K7Po54IG/WQA+akf7PvlFIxOQa11asteQ46Jd4z8HUSaSS92EY0Os+OA6ewIuvBaLC3rrCnLYbPQ1P4kAnjSe0kS/Lyb55n6lZvP9GarFzAogaXNK/iKP+8uOwn8mOpE1GVchShMRWY7Rt/CI3vhEAl74t45Mglfff9/lSNyQNDX6rPI+LWkccj1tFa1FKyICfWb83uOJGMdtwmAGBoFaBPjB6SyctOBOlTUPKaR+2H6vexsgBPITI3Cy2WkNMSMVb/xkKvxbfbWAjqzdH8kbh/bmY6pqsLQcVPqoolvV8IPg0hk+L1P5Q85Pn+5kIS5ME5v2nFDUE+XRsZDLO09bv9UoJko0D3sRQINdzz0L0m5r3wjVOu3JC/mXdsUCyrH5qGcbK99jJs8/Gx+RoQk+k034WO5wNMsbNXJiEUEEFT5e5YCC+U5/8dPpgOcDZ6ME4=
    skip_cleanup: true
    file_glob: true
    file: 'deploy/*'
    draft: true
    on:
      tags: true
  - provider: cargo
    on:
      tags: true
      condition: $DEPLOYABLE = true
    token:
      secure: X62/N5+y1REYd10r+6/YABmGwMAQV2iEQBhhCRHAPOvz4bO72FNsqMnt2DjM1wMBRYFv4wwU5i9wkPJoaRQiGD9f8DbPsVy15aHrfSOFqoHnSCJ9jDO3pjt92kcj3y2Oqkb3O7J7+kim8N8905XPcdwQmn1Y5zF+zwxjy5J1bvyXPA+ZwwsdakpXhxoQ1qqtdz8HUX7nXRhtZphLYlYeYUS05+Vi5G/7W7mAOgaaX5up/RX1qd/neSRiC5Kap5WF6QgRmZOcNw+MM/NpTaCTEQ4pBkepMxpA/9+jilHh4zDPjUb/xtFHrfUXcSVCCbdQ44iwYAdwP2NXMsaiDRgQ8rfABI/rohCrMiFuOBraBJLy1aq9jEfNKcBjQabe12KHdWNS5q62NOlt9JfEzQpzFytDzLNRFdiywb8d5P76tLh++10cSnDi32HSt95wWimOTCR5Jm2wHjp5/hgwRIZy7m6FnUIpXQIVezpZIOfAMuEbEefX1v/vXR9WTAo4R9+Ov+HkarZVYH+o3Rwkz4dD6VTcAfW86Fn+ptyWtIxM8zzK8/vPPC6PXYh54vQq2Iz53o/8YV1tUK3UXBB7EZM9NWhwCFROHSsd1yQ3yw+fyjyUnYYBtT4JRHZ5G56S0/k7OOgFbvUGMYIq5vn+SMfpeQvx0DfK1prqn9ZicwbcrUs=
