name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static-analysis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo components
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: Rust Format
        run: cargo fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature_build: [no-default, default]
    env:
      FEATURE_BUILD: ${{matrix.feature_build}}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for default features on linux
        if: matrix.feature_build == 'default'
        run: sudo apt-get install libdbus-1-dev libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0-dev libxcb-xfixes0
      - name: Build
        run: .ci/build.sh
      - name: Run tests
        run: .ci/test.sh
  build-mac:
    runs-on: macos-10.15
    env:
      FEATURE_BUILD: ${{matrix.feature_build}}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: .ci/build.sh
      - name: Run tests
        run: .ci/test.sh
