on:
  push:
    tags:
      - '*'

name: Build, Release, Publish to GH and Cargo

jobs:
  release:
    name: Release Build
    strategy:
      matrix:
        build:
          - name: 'linux-no-features'
            type: linux
            features: no-default
            os: ubuntu-latest
          - name: 'linux'
            type: linux
            features: default
            os: ubuntu-latest
          - name: 'macos'
            type: mac
            features: default
            os: macos-10.15
    runs-on: ${{matrix.build.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies for default features on linux
        if: matrix.build.features == 'default' && matrix.build.type == 'linux'
        run: sudo apt-get install libdbus-1-dev libxcb-shape0 libxcb-shape0-dev libxcb-xfixes0-dev libxcb-xfixes0
      - name: build
        env:
          FEATURE_BUILD: ${{matrix.build.features}}
        run: .ci/build.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          draft: true
          prerelease: false
      - name: Prepare for upload
        env:
          DEPLOY_NAME: ${{matrix.build.name}}
        run: .ci/setup_deploy.sh
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./deploy/otpcli.${{matrix.build.name}}.tar.xz
          asset_name: otpcli-${{matrix.build.type}}-${{martrix.build.features}}
          asset_content_type: application/tar
